[General]
Font="JetBrainsMono Nerd Font"
FontSize=14
ClockEnabled="false"
CustomBackground="true"
LoginBackground="false"
Background="file:///var/lib/sddm-wallpaper.jpg"
UserIcon="true"

# Uncomment this option to show the last letter of the password
# for the number of milliseconds specified
# PasswordShowLastLetter=1000
