-- Generated by nwg-displays on 2026-08-13 at 17:41:45. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.03",
    position = "9905x6547",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "3840x2160@60.0",
    position = "8984x4387",
    scale = 1.0
})
